### ISSUE TITLE
Matrix-Vector-Multiplication

### ISSUE THREAD

**Issue by stexa** [cospectrum/microgemm#25]
In ndarray I had huge benefits from using the general_mat_vec_mul compared to general_mat_mul with a one-dimensional matrix. Is it something you are interested in implementing or is the performance benefit mainly about different settings in PackSizes and Kernel?

Sry, I don't know much about gemm-magic, I just benchmarked my way through different systems and implementations :D

**Comment by cospectrum** [comment]
Hello. I think you are talking about `gemv`: general matrix-vector multiplication. 
`gemm` is optimized specifically for matrix-matrix multiplication (of large sizes), so it doesn't work very well with vectors.

**Comment by stexa** [comment]
Yes, this is what I meant.

**Comment by cospectrum** [comment]
No, gemv doesn't belong here. No plans
